name: Publish to PyPI

on:
  push:
    tags:
      - 'v*.*.*'
      - '*.*.*'

jobs:
  pypi-publish:
    name: Build and publish Python 🐍 distribution 📦 to PyPI
    runs-on: ubuntu-latest
    
    environment:
      name: pypi
      url: https://pypi.org/p/leadsheetanalyser
      
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
      contents: read
      
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup PDM
      uses: pdm-project/setup-pdm@v4
      with:
        python-version: "3.12"
        
    - name: Install dependencies
      run: pdm install
      
    - name: Build package
      run: pdm build
      
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
